### ISSUE TITLE
Adjust minimap size epic minimap (2)

### ISSUE THREAD

**Issue by RenzoRichter** [claassenlab/cellpose#11]
**As a** Cellpose user **I want** to be able to adjust the size of the minimap window **so that** I can make it my preferred size.

**Acceptance criteria:**

- [x] The user can adjust the size of the minimap window
- [x] The content of the minimap window also adjusts in size as the window is adjusted

**Comment by jakobjo** [comment]
Implementation of  the resizability of the minimap is too much effort, therefore we skip this part of the epic and potentially look back at it later).

**Comment by jakobjo** [comment]
It was wisehd to still have that feature on the minimap, now that its implemented.
