### ISSUE TITLE
Orientation on minimap epic minimap (2)

### ISSUE THREAD

**Issue by RenzoRichter** [claassenlab/cellpose#12]
**As a** Cellpose user **I want** the minimap to highlight the area currently displayed on the main screen,
**so that** I can understand which part of the image I'm currently viewing.

**Acceptance criteria:**

- [ ] The part of the picture that is viewed in the main cellpose window is outlined in white or grey.
- [ ] The minimap window is updated in real time, so that it accurately reflects the currently displayed area.

_Note: Illustration_ of the idea (no need for these buttons, just to vaguely illustrate the idea):
![Image](https://github.com/claassenlab/cellpose/assets/166049959/a6133e05-872e-466f-be8f-0f9d341ed983)

**Comment by jakobjo** [comment]
This issue has been split into 3 more detailed issues:

#40 
#41 
#42
